// <auto-generated />
using DCS_Compendium;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DCS_Compendium.Migrations
{
    [DbContext(typeof(VehicleContext))]
    partial class VehicleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DCS_Compendium.VehicleDBSetup", b =>
                {
                    b.Property<int>("VehicleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleID"));

                    b.Property<string>("VehicleClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleWeakness")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleID");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleID = 1,
                            VehicleClass = "Ground",
                            VehicleDescription = "Russian Anti-Air Platform with no self radar, but uses radar from external sources to be guided.",
                            VehicleImagePath = "Resources\\SA-3 Goa",
                            VehicleName = "SA-3 Goa",
                            VehicleType = "Anti-Air",
                            VehicleWeakness = "Chaff, Terrain, Notching"
                        },
                        new
                        {
                            VehicleID = 2,
                            VehicleClass = "Ground",
                            VehicleDescription = "Russian Anti-Air Vehicle with a SARH system.",
                            VehicleImagePath = "Resources\\SA-6 Kub",
                            VehicleName = "SA-6 Kub",
                            VehicleType = "Anti-Air",
                            VehicleWeakness = "Chaff, Terrain, Notching"
                        },
                        new
                        {
                            VehicleID = 3,
                            VehicleClass = "Ground",
                            VehicleDescription = "Amphibious Russian Wheeled Anti-Air Vehicle with SARH radar.",
                            VehicleImagePath = "Resources\\SA-8 OSA",
                            VehicleName = "SA-8 OSA",
                            VehicleType = "Anti-Air",
                            VehicleWeakness = "Chaff, Terrain, Notching"
                        },
                        new
                        {
                            VehicleID = 4,
                            VehicleClass = "Ground",
                            VehicleDescription = "Russian short-range wheeled Anti-Air system.",
                            VehicleImagePath = "Resources\\SA-9 Strela",
                            VehicleName = "SA-9 Strela",
                            VehicleType = "Anti-Air",
                            VehicleWeakness = "Flares"
                        },
                        new
                        {
                            VehicleID = 5,
                            VehicleClass = "Ground",
                            VehicleDescription = "Russian Anti-Air Vehicle with 30mm cannons and Anti-Air Missiles.",
                            VehicleImagePath = "Resources\\SA-19 Tunguska",
                            VehicleName = "SA-19 Tunguska",
                            VehicleType = "Anti-Air",
                            VehicleWeakness = "Chaff, Terrain, Notching"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
